"""empty message

Revision ID: cc1c783b17cd
Revises: 50b3bebb1986
Create Date: 2024-11-21 13:58:37.528422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1c783b17cd'
down_revision: Union[str, None] = '50b3bebb1986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('favorite', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'favorite')
    # ### end Alembic commands ###
